# An example of a config.yaml file showing all possible options. If no
# config.yaml file exists, opentopodata will load example-config.yaml instead.


# 400 error will be thrown above this limit.
max_locations_per_request: 100 

# CORS header. Should be None for no CORS, '*' for all domains, or a url with
# protocol, domain, and port ('https://api.example.com/'). Default is null.
access_control_allow_origin: null

datasets:

# A small testing dataset is included in the repo.
- name: lidar5m
  path: /media/franz/Koala/LiDAR5m/full/

- name: srtm30m
  path: /media/franz/Koala/SRTMGL_OpenTopoData/geotiff/
  fallback: true
  
# Example config for 90 metre SRTM.
# - name: srtm90m
#   path: data/srtm-90m-nasa-v3.0/
#   filename_epsg: 4326  # This is the default value.
#   filename_tile_size: 1  # This is the default value.
